### PR TITLE
Add a basic GHA CI that downloads all versions of the JDKs

### PR DESCRIPTION
**Pull request by vasilmkd**
I will follow this up with a more rigorous test that verifies the installed JDK version.

### CODE REVIEW

**Comment by vasilmkd** [comment]
I don't quite understand why the GHA are not running on this PR.

**Comment by vasilmkd** [comment]
It ran on my fork https://github.com/vasilmkd/jdk-index/runs/3686568856?check_suite_focus=true.

**Comment by vasilmkd** [comment]
Here's a GHA run where I intentionally broke the index: https://github.com/vasilmkd/jdk-index/actions/runs/1265569197.

**Comment by vasilmkd** [comment]
And the run after the revert: https://github.com/vasilmkd/jdk-index/actions/runs/1265575243.

**Review by rossabaker — APPROVED** [review]
That's a very good question.  Should we merge it and see if it starts running subsequently?

**Comment by vasilmkd** [comment]
Yeah, I don't have any other ideas, I tried pushing new commits, force pushing, nothing worked.

**Comment by vasilmkd** [comment]
I will go ahead and merge this and report the outcome.

**Comment by vasilmkd** [comment]
GitHub Actions picked up the merge and here is the run https://github.com/typelevel/jdk-index/actions/runs/1266066685.

Must have been an issue on their part previously.

**Pull request merged**
