### PR TITLE
Generate the index from Scala sources

### PR DESCRIPTION
**Pull request by vasilmkd**
Use Scala code as the single source of truth.

### CODE REVIEW

**Review by rossabaker — COMMENTED** [review]
Are you looking at making index.scala smarter?  Fetching from some other source?  Reducing boilerplate with the magic of functors?  index.scala is basically index.json with types, which might also have been achieved with a JSON schema.  This seems like a power tool for a simple job, but maybe you have grander ambitions.  Or maybe you just like writing Scala. :smile:

**Comment by vasilmkd** [comment]
I really just wanted to try out Scala 3, so, guilty. I do agree that `index.scala` right now is just JSON with types. There are APIs that could be called to generate this index in the future though, like [this one](https://github.com/foojayio/discoapi).

By functors, do you mean the transformation of the list to the nested stringified map? It was a quick and dirty solution, it can definitely be improved.

**Comment by rossabaker** [comment]
> By functors, do you mean

Oh, I just picked an arbitrary typeclass for literary effect, but what's there looks roughly like a product of OS, versions, etc.  And could be generated with a simple for-comprehension.

**Comment by vasilmkd** [comment]
Ok, I've given it some thought. New JDKs come out once every three months. Full on automation with automatic discovery is IMO not worth it, because we're only looking to maintain a couple of distributions (adoptium and graalvm) for the purposes of Typelevel projects, and the diff is a couple of web links that are easily obtainable.

Typelevel projects on the other hand, all default to the latest available JDK build of a given version. For people wanting to pin a specific version/build of Java, they can do that by circumventing the jabba index altogether. To wit, we should merge #5.

Regarding this particular PR, I did want to write some Scala 3, and I kind of started out with the intent of having the project follow `sbt-github-actions` in making the strongly-typed Scala code be the only source of truth, with the final JSON just a render of it. I will look into simplifying things further before merging.

It also helps both with the generation of the JSON and verification of the index in the CI, so I would like to have it around, it increases the confidence that we won't be making changes that will break Typelevel builds.

@rossabaker, interested to hear your thoughts. Hopefully, I've made a coherent and convincing argument.

**Comment by rossabaker** [comment]
I am on board with all of that.

**Review by rossabaker — APPROVED** [review]

**Pull request merged**
