### PR TITLE
Much simpler index, in preparation for `download-java`

### PR DESCRIPTION
**Pull request by vasilmkd**
@armanbilge

### CODE REVIEW

**Comment by armanbilge** [comment]
Oh yeah, this is super good 👍  so it's nested OS/arch/distribution/JDK version. Awesome.

**Comment by vasilmkd** [comment]
Basically, no more special versions for GraalVM and OpenJ9, people should only select the JDK version (17, 11 or 8) and they will get the latest available version that matches.

**Comment by vasilmkd** [comment]
This is still jabba specific, I will create the file based structure for download-jdk.

**Comment by armanbilge** [comment]
Yeah I think that makes good sense. What we can do is provide a way for users to give hash commit and/or url so that they can pin to an old version of the index if they want to.

**Comment by armanbilge** [comment]
> This is still jabba specific, I will create the file based structure for download-jdk. In a separate PR.

Yeah that's probably good 😆 although then there's no excuse to make a Scala.js action :P

**Comment by vasilmkd** [comment]
This still contains some cruft that jabba requires, like each url being prefixed by "tgz+url" for tar.gz files and "zip+url" for zip files. It's just weird.

**Pull request merged**
